products/urls.py
from django.urls import path
from . import views
app_name = "products"

urlpatterns = [
    path('', views.index, name="index"),
    path('addtocart/<int:productid>',
         views.addtocart, name="addtocarts")
    # path('new', views.newproducts),


]

pyshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
]

products/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    image_url = models.CharField(max_length=2083)

    def __str__(self):
        return self.name


class Offer(models.Model):
    code = models.CharField(max_length=255)
    description = models.CharField(max_length=1000)
    discount = models.FloatField()

    def __str__(self):
        return self.code


class ProductSelected(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)  # user specify korlam
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quanity = models.IntegerField(default=1)
    order = models.BooleanField(default=False)

products/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product


def index(request):
    products = Product.objects.all()
    return render(request, "index.html", {'products': products})


def addtocart(request):
    print(request.user, 'habijabi')
    return None

products/templates/index.html
{% extends 'base.html'%}

{% block content %}
<h1>Products</h1>
<div class="row">
    {% for product in products %}
    <div class="col-sm-4">
        <div class="card" style="margin-bottom:20px">
            <img src="{{ product.image_url}}" style="height: 167px !important;max-width: 224px;
            margin: auto;" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">${{ product.price }}</p>
                <!-- <a href="{% url 'products:addtocarts' product.id %}" class="btn btn-primary">Add to Cart</a> -->
                <a href="addtocart/{{product.id}}" class="btn btn-primary">Add to Cart</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">The GROWcery Shop</a>
    </nav>
    <div>
        <div class="container">
            {% block content%}
            {% endblock %}
        </div>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>